In [3]:
# Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import BayesianRidge
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn import metrics
from sklearn.naive_bayes import BernoulliNB
from scipy import stats
import numpy as np
import warnings

#--------------------------------#
# To use later
def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()
# To use later
#--------------------------------#
    
# Encode labels with value 0-> n_classes -1
le = preprocessing.LabelEncoder()

# Read excel with Pandas library
path_to_dataset = "../datasets/appliances_combination.xls"
#path_to_dataset= "../datasets/one_appliance.xls"

df = pd.read_excel(path_to_dataset)

# These columns will be our features - X
features = ['I50', 'Φ50', 'I150', 'Φ150', 'I250', 'Φ250']

# Features - X
X = df[features]

# Calculate Z-score in order to find outliers
z = np.abs(stats.zscore(X))
print(z) # Visualize
threshold = 2.5 # Change the threshold arbitrarily
print(np.where(z > threshold))
df = df[(z < threshold).all(axis=1)] # Remove outliers that exceed the threshold given from dataset

# Now get as X the 'clean' features
X = df[features]

# Scale the inputs (4 options; put comment in the ones you are not using)

# -1- Standard Scaling
#scaler = StandardScaler()
#X = scaler.fit_transform(X)

# -2- Min-max scaling 
#scaler = preprocessing.MinMaxScaler()
#X = scaler.fit_transform(X)

# -3- Robust scaling
scaler = preprocessing.RobustScaler()
X = scaler.fit_transform(X)

# -4- Normalizing
#scaler = preprocessing.Normalizer()
#X = scaler.fit_transform(X)

# Label - Y
y = df['appliance']

# Convert y to integer 
le.fit(y) # Fit label encoder
y = le.transform(y) # Transform labels to normalized encoding

# Split to train & test set 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform Logistic Regression
reg = LogisticRegression().fit(X_train, y_train)

y_pred = reg.predict(X_test)
print("Logistic Regression:")
print("\nAccuracy: %1.3f" % reg.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

# Bayesian Ridge
#bayess = BayesianRidge().fit(X_train, y_train)

#y_pred = bayess.predict(X_test)
#print("Bayesian Ridge:\n")
#print("Accuracy: %1.3f" % bayess.score(X_test, y_test))
#print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
#print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
#print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
#print("-----------------\n")

# Naive Bayes Bernoulli 
clf = BernoulliNB()
clf.fit(X_train, y_train)
BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)
y_pred = clf.predict(X_test)

print("Naive Bayes Bernoulli:")
print("\nAccuracy: %1.3f" % clf.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

# Some warnings are presented because we got some negative values with NBB.
# TODO: Fix it? 

# Decision Trees
clf = DecisionTreeClassifier(random_state = 42) # Feel free to change 'min_samples_split' 
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Decision Trees:")
print("\nAccuracy: %1.3f" % clf.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

[[0.45594385 0.16532287 0.0946546  0.94436727 0.02791146 0.14068024]
 [0.33151664 0.11597225 0.09209629 0.93473174 0.01952717 0.09073563]
 [0.33178331 4.39312762 0.09213199 0.14957256 0.0196669  2.77994068]
 ...
 [0.11525167 0.29800554 0.10478672 1.15376947 0.05299699 0.54259607]
 [0.14485144 0.42320819 0.10687502 0.91244958 0.05055157 0.40170997]
 [0.20245099 0.37401068 0.10414417 0.88655409 0.0533114  0.42155767]]
(array([    2,     2,    73, ..., 27660, 27660, 27677]), array([1, 5, 1, ..., 1, 5, 1]))
Logistic Regression:

Accuracy: 0.431
Precision: 0.386
Recall: 0.431
F1-Score: 0.353
-----------------

Naive Bayes Bernoulli:

Accuracy: 0.358
Precision: 0.282
Recall: 0.358
F1-Score: 0.289
-----------------

Decision Trees:

Accuracy: 0.888
Precision: 0.889
Recall: 0.888
F1-Score: 0.888
-----------------



/home/klajdi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/klajdi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
