In [2]:
# Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import BayesianRidge
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn import metrics
from sklearn.naive_bayes import BernoulliNB
from scipy import stats
import numpy as np
import warnings

#--------------------------------#
# To use later
def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()
# To use later
#--------------------------------#
    
# Encode labels with value 0-> n_classes -1
le = preprocessing.LabelEncoder()

# Read excel with Pandas library
path_to_dataset = "../datasets/one_appliance.xls"
df = pd.read_excel(path_to_dataset)

# These columns will be our features - X
features = ['I50', 'Φ50', 'I150', 'Φ150', 'I250', 'Φ250']

# Features - X
X = df[features]

# Calculate Z-score in order to find outliers
z = np.abs(stats.zscore(X))
print(z) # Visualize
threshold = 2.5 # Change the threshold arbitrarily
print(np.where(z > threshold))
df = df[(z < threshold).all(axis=1)] # Remove outliers that exceed the threshold given from dataset

# Now get as X the 'clean' features
X = df[features]

# Scale the inputs (4 options; put comment in the ones you are not using)

# -1- Standard Scaling
#scaler = StandardScaler()
#X = scaler.fit_transform(X)

# -2- Min-max scaling 
#scaler = preprocessing.MinMaxScaler()
#X = scaler.fit_transform(X)

# -3- Robust scaling
scaler = preprocessing.RobustScaler()
X = scaler.fit_transform(X)

# -4- Normalizing
#scaler = preprocessing.Normalizer()
#X = scaler.fit_transform(X)

# Label - Y
y = df['appliance']

# Convert y to integer 
le.fit(y) # Fit label encoder
y = le.transform(y) # Transform labels to normalized encoding

# Split to train & test set 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform Logistic Regression
reg = LogisticRegression().fit(X_train, y_train)

y_pred = reg.predict(X_test)
print("Logistic Regression:")
print("\nAccuracy: %1.3f" % reg.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

# Bayesian Ridge
#bayess = BayesianRidge().fit(X_train, y_train)

#y_pred = bayess.predict(X_test)
#print("Bayesian Ridge:\n")
#print("Accuracy: %1.3f" % bayess.score(X_test, y_test))
#print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
#print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
#print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
#print("-----------------\n")

# Naive Bayes Bernoulli 
clf = BernoulliNB()
clf.fit(X_train, y_train)
BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)
y_pred = clf.predict(X_test)

print("Naive Bayes Bernoulli:")
print("\nAccuracy: %1.3f" % clf.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

# Some warnings are presented because we got some negative values with NBB.
# TODO: Fix it? 

# Decision Trees
clf = DecisionTreeClassifier(random_state = 42) # Feel free to change 'min_samples_split' 
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Decision Trees:")
print("\nAccuracy: %1.3f" % clf.score(X_test, y_test))
print("Precision: %1.3f" % metrics.precision_score(y_test, y_pred, average ='weighted'))
print("Recall: %1.3f" % metrics.recall_score(y_test, y_pred, average ='weighted'))
print("F1-Score: %1.3f" % metrics.f1_score(y_test, y_pred, average ='weighted'))
print("-----------------\n")

[[0.57221048 0.71836518 1.71079118 0.55571547 1.65751708 0.9930963 ]
 [0.73236606 0.07461438 1.05744451 1.48034787 1.00569838 0.88175599]
 [0.06248437 0.37559931 1.23910033 0.89870615 0.22293022 0.83663876]
 ...
 [0.73092353 1.57890977 1.05808091 1.25729583 1.00774584 0.75079358]
 [0.73112794 1.58161404 1.05974868 1.68251831 1.00463818 0.00652814]
 [0.73121985 1.59107898 1.06231303 1.24268337 1.00577343 1.52790048]]
(array([    3,  1801,  1802, ..., 21972, 21974, 21976]), array([5, 5, 5, ..., 3, 5, 3]))
Logistic Regression:

Accuracy: 0.931
Precision: 0.936
Recall: 0.931
F1-Score: 0.927
-----------------

Naive Bayes Bernoulli:

Accuracy: 0.616
Precision: 0.622
Recall: 0.616
F1-Score: 0.544
-----------------

Decision Trees:

Accuracy: 0.980
Precision: 0.980
Recall: 0.980
F1-Score: 0.980
-----------------



/home/klajdi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/klajdi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
